services:
  # Backend API Server
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.api.env
    restart: unless-stopped

  # Queue Workers
  workers:
    build:
      context: ./workers
      dockerfile: Dockerfile
    env_file:
      - ./.workers.env
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: unless-stopped